import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Wifi } from "lucide-react";
import { useApi } from "../context";
import { Loading, PageHeader } from "../ui";
import type { ModelConfigurationState, RetrievalConfiguration } from "../types";

export function ConfigurationPage() {
  const api = useApi(); const client = useQueryClient();
  const providers = useQuery({ queryKey: ["providers", api.connection], queryFn: () => api.providers() });
  const models = useQuery({ queryKey: ["models", api.connection], queryFn: () => api.modelConfiguration() });
  const retrieval = useQuery({ queryKey: ["retrieval-config", api.connection], queryFn: () => api.retrievalConfiguration() });
  const catalog = useQuery({ queryKey: ["memory-catalog", api.connection], queryFn: () => api.catalog() });
  return <><PageHeader eyebrow="STORE-WIDE SETUP" title="Configuration" description="Choose generation and embedding models, then tune how retrieval expands and abstains." />
    <div className="configuration-grid"><ModelSettings providers={providers.data?.providers || []} state={models.data} onSaved={() => client.invalidateQueries({ queryKey: ["models"] })} /><RetrievalSettings value={retrieval.data} routeNames={(catalog.data?.retrieval_routes || []).map(item => item.name)} onSaved={() => client.invalidateQueries({ queryKey: ["retrieval-config"] })} /></div>
  </>;
}

function ModelSettings({ providers, state, onSaved }: { providers: Array<{ id: string; display_name: string; roles: Array<"completion" | "embedding">; credential_env?: string | null; credential_configured: boolean }>; state?: ModelConfigurationState; onSaved: () => void }) {
  const api = useApi(); const [draft, setDraft] = useState<ModelConfigurationState | null>(null); const [confirmRebuild, setConfirmRebuild] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (state) setDraft(structuredClone(state)); }, [state]);
  if (!draft) return <section className="settings-card"><Loading label="Loading model configuration" /></section>;
  const change = (role: "completion" | "embedding", field: string, value: string) => setDraft(current => current ? ({ ...current, configuration: { ...current.configuration, [role]: { ...current.configuration[role], [field]: value || null } } }) : current);
  const save = async () => { try { setMessage("Saving…"); await api.saveModels(draft, confirmRebuild); setMessage("Model configuration saved."); onSaved(); } catch (error) { setMessage((error as Error).message); } };
  return <section className="settings-card"><header><div><span className="kicker">MODELS</span><h2>Completion and embeddings</h2></div><span className="revision">revision {draft.configuration.revision}</span></header>{(["completion", "embedding"] as const).map(role => <div className="model-role" key={role}><div><h3>{role === "completion" ? "Completion" : "Embedding"}</h3><p>{role === "completion" ? "Extraction, grounded answers, and image understanding." : "Semantic indexing and retrieval. A change may rebuild the index."}</p></div><div className="form-grid"><label><span>Provider</span><select value={draft.configuration[role].provider} onChange={e => change(role, "provider", e.target.value)}>{providers.filter(item => item.roles.includes(role)).map(item => <option value={item.id} key={item.id}>{item.display_name}{!item.credential_configured && item.credential_env ? ` · needs ${item.credential_env}` : ""}</option>)}</select></label><label><span>Model ID</span><input value={draft.configuration[role].model || ""} onChange={e => change(role, "model", e.target.value)} placeholder={role === "completion" ? "Provider model ID" : "Embedding model ID"} /></label><label className="wide-field"><span>Custom base URL <em>optional</em></span><input value={draft.configuration[role].base_url || ""} onChange={e => change(role, "base_url", e.target.value)} /></label></div><button className="quiet test-button" onClick={async () => { const value = await api.testModel(role, draft.configuration[role]); setMessage(value.message); }}><Wifi size={14} /> Test {role}</button></div>)}<label className="checkbox-row"><input type="checkbox" checked={confirmRebuild} onChange={e => setConfirmRebuild(e.target.checked)} /><span>Confirm a staged embedding rebuild if the embedding selection changes.</span></label><footer><p>{message || state?.message}</p><button className="primary" onClick={save}>Save models</button></footer></section>;
}

function RetrievalSettings({ value, onSaved, routeNames }: { value?: RetrievalConfiguration; onSaved: () => void; routeNames: string[] }) {
  const api = useApi(); const [draft, setDraft] = useState<RetrievalConfiguration | null>(null); const [message, setMessage] = useState(""); useEffect(() => { if (value) setDraft({ ...value }); }, [value]);
  if (!draft) return <section className="settings-card"><Loading label="Loading retrieval settings" /></section>;
  const number = (key: keyof RetrievalConfiguration, next: string) => setDraft(current => current ? { ...current, [key]: Number(next) } : current);
  const available = routeNames.length ? routeNames : draft.enabled_routes;
  const reset = () => setDraft(current => current ? { ...current, default_top_k: 12, max_context_items: 24, max_context_tokens: 6000, per_source_context_tokens: 2000, max_refinement_rounds: 2, graph_hops: 2, confidence_margin: .018, deep_recall_enabled: true, answer_abstain_threshold: .1, retrieval_profile: "auto", enabled_routes: available, route_weights: {} } : current);
  const toggleRoute = (name: string) => setDraft(current => {
    if (!current) return current;
    const enabled = current.enabled_routes.includes(name)
      ? current.enabled_routes.filter(item => item !== name)
      : [...current.enabled_routes, name];
    return { ...current, enabled_routes: enabled.length ? enabled : current.enabled_routes };
  });
  const save = async () => { try { const saved = await api.saveRetrieval(draft); setDraft(saved); setMessage("Retrieval settings saved."); onSaved(); } catch (error) { setMessage((error as Error).message); } };
  return <section className="settings-card"><header><div><span className="kicker">RETRIEVAL</span><h2>Search and grounding</h2></div><span className="revision">revision {draft.revision}</span></header><div className="setting-list"><label className="number-setting"><div><strong>Retrieval profile</strong><span>Auto detects the source intent; fixed profiles tune route weights.</span></div><select value={draft.retrieval_profile} onChange={e => setDraft(current => current ? { ...current, retrieval_profile: e.target.value as RetrievalConfiguration["retrieval_profile"] } : current)}>{["auto", "balanced", "precise", "broad", "mixed", "code", "table", "image", "document", "conversation"].map(value => <option value={value} key={value}>{value}</option>)}</select></label><NumberSetting label="Default results" detail="Evidence returned for a normal search." value={draft.default_top_k} min={1} max={100} onChange={value => number("default_top_k", value)} /><NumberSetting label="Maximum answer context" detail="Most Trace records allowed into answer context." value={draft.max_context_items} min={draft.default_top_k} max={100} onChange={value => number("max_context_items", value)} /><NumberSetting label="Context token budget" detail="Approximate total token ceiling for grounded evidence." value={draft.max_context_tokens} min={256} max={200000} onChange={value => number("max_context_tokens", value)} /><NumberSetting label="Per-source token budget" detail="Prevents one source from crowding out every other source." value={draft.per_source_context_tokens} min={128} max={draft.max_context_tokens} onChange={value => number("per_source_context_tokens", value)} /><NumberSetting label="Refinement rounds" detail="How often a low-confidence query can be rewritten." value={draft.max_refinement_rounds} min={0} max={2} onChange={value => number("max_refinement_rounds", value)} /><NumberSetting label="Graph hops" detail="Connection depth used while grounding." value={draft.graph_hops} min={0} max={4} onChange={value => number("graph_hops", value)} /><NumberSetting label="Confidence margin" detail="Required score separation before accepting a route." value={draft.confidence_margin} min={0} max={1} step="0.001" onChange={value => number("confidence_margin", value)} /><NumberSetting label="Abstain threshold" detail="Minimum top score required to answer." value={draft.answer_abstain_threshold} min={0} max={1} step="0.01" onChange={value => number("answer_abstain_threshold", value)} /><label className="switch-row"><div><strong>Deep Recall</strong><span>Expand the route when normal retrieval remains uncertain.</span></div><input type="checkbox" checked={draft.deep_recall_enabled} onChange={e => setDraft(current => current ? { ...current, deep_recall_enabled: e.target.checked } : current)} /></label>
    <div className="route-toggles"><strong>Enabled routes</strong><div>{available.map(name => <label key={name}><input type="checkbox" checked={draft.enabled_routes.includes(name)} onChange={() => toggleRoute(name)} />{name}</label>)}</div></div>
    <div className="route-weights"><strong>Route weights</strong><div>{available.map(name => <label key={name}><span>{name}</span><input type="number" min={0} max={5} step="0.1" value={draft.route_weights[name] ?? 1} onChange={event => setDraft(current => current ? { ...current, route_weights: { ...current.route_weights, [name]: Number(event.target.value) } } : current)} /></label>)}</div></div>
  </div><footer><p>{message}</p><button className="quiet" onClick={reset}>Reset defaults</button><button className="primary" onClick={save}>Save retrieval</button></footer></section>;
}
function NumberSetting({ label, detail, value, onChange, ...input }: { label: string; detail: string; value: number; onChange: (value: string) => void; min: number; max: number; step?: string }) { return <label className="number-setting"><div><strong>{label}</strong><span>{detail}</span></div><input type="number" value={value} onChange={e => onChange(e.target.value)} {...input} /></label>; }
