import { FormEvent, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Database, HelpCircle, Wifi } from "lucide-react";
import { useApi } from "../context";
import { PageHeader } from "../ui";
import { classNames } from "../util";
import type { Connection } from "../types";

export function ConnectionPage({ value, onSave }: { value: Connection; onSave: (value: Connection) => void }) {
  const api = useApi(); const client = useQueryClient(); const [draft, setDraft] = useState(value); const [message, setMessage] = useState(""); const session = useQuery({ queryKey: ["session", api.connection], queryFn: () => api.session() });
  const save = async (event: FormEvent) => { event.preventDefault(); sessionStorage.setItem("trisynapse.baseUrl", draft.baseUrl); sessionStorage.setItem("trisynapse.token", draft.token); localStorage.setItem("trisynapse.namespace", JSON.stringify(draft.namespace)); onSave(draft); setMessage("Connection saved for this browser tab."); await client.invalidateQueries(); };
  return <><PageHeader eyebrow="SERVER + ISOLATION" title="Connection" description="Connect Studio to a memory server and choose the namespace applied to every operation." />
    <div className="connection-layout"><form className="settings-card connection-card" onSubmit={save}><header><div><span className="kicker">SERVER</span><h2>API connection</h2></div><span className={`connection-role ${session.data?.role || "unknown"}`}>{session.data?.role || "not connected"}</span></header><label><span>API base URL</span><input value={draft.baseUrl} onChange={e => setDraft({ ...draft, baseUrl: e.target.value.replace(/\/$/, "") })} placeholder="Same origin" /><small>Leave empty when Studio is served by the Trisynapse server.</small></label><label><span>Bearer token</span><input type="password" autoComplete="off" value={draft.token} onChange={e => setDraft({ ...draft, token: e.target.value })} placeholder="Token from the memory store" /><small>Kept in session storage only and never written to the server database.</small></label><div className="divider" /><span className="kicker">NAMESPACE</span><div className="form-grid"><NamespaceField label="Project ID" value={draft.namespace.project_id} onChange={project_id => setDraft({ ...draft, namespace: { ...draft.namespace, project_id } })} required /><NamespaceField label="User ID" value={draft.namespace.user_id || ""} onChange={user_id => setDraft({ ...draft, namespace: { ...draft.namespace, user_id: user_id || null } })} /><NamespaceField label="Agent ID" value={draft.namespace.agent_id || ""} onChange={agent_id => setDraft({ ...draft, namespace: { ...draft.namespace, agent_id: agent_id || null } })} /><NamespaceField label="Session ID" value={draft.namespace.session_id || ""} onChange={session_id => setDraft({ ...draft, namespace: { ...draft.namespace, session_id: session_id || null } })} /></div><footer><p>{message}</p><button className="primary">Save and reconnect</button></footer></form><aside className="connection-info"><div className={classNames("connection-health", session.isSuccess && "ready", session.isError && "error")}><Wifi size={21} /><div><strong>{session.isSuccess ? "Connection ready" : session.isError ? "Connection failed" : "Checking connection"}</strong><p>{session.isError ? (session.error as Error).message : session.data ? `${session.data.role} access to ${session.data.effective_namespace.project_id}` : "Reading server capabilities…"}</p></div></div><article><HelpCircle size={18} /><div><strong>Custom servers and CORS</strong><p>A different API origin must explicitly allow the Studio origin. Same-origin serving needs no CORS setup.</p></div></article><article><Database size={18} /><div><strong>Namespace isolation</strong><p>Project, user, agent, and session identifiers scope sources, queries, Trace records, and graph views together.</p></div></article></aside></div>
  </>;
}
function NamespaceField({ label, value, onChange, required }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label><span>{label}</span><input value={value} onChange={e => onChange(e.target.value)} required={required} /></label>; }
