"""Trace & Recall engine implementation.

The public :class:`MemoryEngine` lives here so applications can import either
``trisynapse_memory.MemoryEngine`` or ``trisynapse_memory.engine.MemoryEngine``.
"""

from trisynapse_memory.engine.memory import MemoryEngine
from trisynapse_memory.engine.formation.sources import LoadedDocument, load_document
from trisynapse_memory.engine.models import (
    Actor,
    Citation,
    CompiledClaim,
    EpisodeInfo,
    EpisodeRecallView,
    MemoryDelta,
    MemoryHistory,
    MemoryGraphEdge,
    MemoryGraphNode,
    MemoryGraphPage,
    MemoryJob,
    MemoryNamespace,
    MemoryPage,
    MemoryQueryResult,
    MemorySearchResult,
    ConnectionTestResult,
    ModelConfiguration,
    ModelConfigurationChange,
    ModelDescriptor,
    ProviderDescriptor,
    ProviderRole,
    ProviderSelection,
    QueryCandidateSnapshot,
    QueryRun,
    QueryRunPage,
    QueryRunRemoveRequest,
    QueryStep,
    RetrievalConfiguration,
    IngestionRun,
    RemoveRequest,
    RemoveResult,
    RecallSnapshot,
    RetrievalTrace,
    SearchHit,
    SnapshotDiff,
    SourceIngestionResult,
    SourceInput,
    SourceRecord,
    SourcePreview,
    SourcePreviewItem,
    StoreValidation,
)
from trisynapse_memory.engine.providers.registry import (
    CompletionProvider,
    EmbeddingRebuildRequired,
    ProviderError,
    ProviderSettings,
)
from trisynapse_memory.engine.retrieval.contracts import (
    HeuristicQueryPlanner,
    QueryPlan,
    QueryPlanner,
    RetrievalDocument,
    RetrievalRoute,
    RouteRegistry,
)
from trisynapse_memory.engine.retrieval.tokenization import (
    ApproximateTokenCounter,
    CallableTokenCounter,
    TokenCounter,
    token_counter_for,
)

__all__ = [
    "Actor",
    "Citation",
    "CompiledClaim",
    "CompletionProvider",
    "ConnectionTestResult",
    "EmbeddingRebuildRequired",
    "EpisodeInfo",
    "EpisodeRecallView",
    "MemoryDelta",
    "MemoryEngine",
    "MemoryHistory",
    "MemoryGraphEdge",
    "MemoryGraphNode",
    "MemoryGraphPage",
    "MemoryJob",
    "MemoryNamespace",
    "MemoryPage",
    "MemoryQueryResult",
    "MemorySearchResult",
    "ModelConfiguration",
    "ModelConfigurationChange",
    "ModelDescriptor",
    "LoadedDocument",
    "ProviderError",
    "ProviderDescriptor",
    "ProviderRole",
    "ProviderSelection",
    "QueryCandidateSnapshot",
    "QueryRun",
    "QueryRunPage",
    "QueryRunRemoveRequest",
    "QueryStep",
    "QueryPlan",
    "QueryPlanner",
    "RetrievalConfiguration",
    "ProviderSettings",
    "IngestionRun",
    "RemoveRequest",
    "RemoveResult",
    "RecallSnapshot",
    "RetrievalTrace",
    "RetrievalDocument",
    "RetrievalRoute",
    "RouteRegistry",
    "HeuristicQueryPlanner",
    "SearchHit",
    "SnapshotDiff",
    "SourceIngestionResult",
    "SourceInput",
    "SourceRecord",
    "SourcePreview",
    "SourcePreviewItem",
    "StoreValidation",
    "TokenCounter",
    "ApproximateTokenCounter",
    "CallableTokenCounter",
    "token_counter_for",
    "load_document",
]
