"""Trace & Recall engine implementation.

The public :class:`MemoryEngine` lives here so applications can import either
``trisynapse_memory.MemoryEngine`` or ``trisynapse_memory.engine.MemoryEngine``.
"""

from trisynapse_memory.engine.memory import MemoryEngine
from trisynapse_memory.engine.loaders import LoadedDocument, load_document
from trisynapse_memory.engine.models import (
    Actor,
    Citation,
    CompiledClaim,
    EpisodeInfo,
    EpisodeRecallView,
    MemoryDelta,
    MemoryHistory,
    MemoryGraphEdge,
    MemoryGraphNode,
    MemoryGraphPage,
    MemoryJob,
    MemoryNamespace,
    MemoryPage,
    MemoryQueryResult,
    MemorySearchResult,
    ConnectionTestResult,
    ModelConfiguration,
    ModelConfigurationChange,
    ModelDescriptor,
    ProviderDescriptor,
    ProviderRole,
    ProviderSelection,
    QueryCandidateSnapshot,
    QueryRun,
    QueryRunPage,
    QueryRunRemoveRequest,
    QueryStep,
    RetrievalConfiguration,
    IngestionRun,
    RemoveRequest,
    RemoveResult,
    RecallSnapshot,
    RetrievalTrace,
    SearchHit,
    SnapshotDiff,
    SourceIngestionResult,
    SourceInput,
    SourceRecord,
    SourcePreview,
    SourcePreviewItem,
    TraceVerification,
)
from trisynapse_memory.engine.privacy import PrivacyFilter, RedactionResult
from trisynapse_memory.engine.providers import (
    CompletionProvider,
    EmbeddingRebuildRequired,
    ProviderError,
    ProviderSettings,
)

__all__ = [
    "Actor",
    "Citation",
    "CompiledClaim",
    "CompletionProvider",
    "ConnectionTestResult",
    "EmbeddingRebuildRequired",
    "EpisodeInfo",
    "EpisodeRecallView",
    "MemoryDelta",
    "MemoryEngine",
    "MemoryHistory",
    "MemoryGraphEdge",
    "MemoryGraphNode",
    "MemoryGraphPage",
    "MemoryJob",
    "MemoryNamespace",
    "MemoryPage",
    "MemoryQueryResult",
    "MemorySearchResult",
    "ModelConfiguration",
    "ModelConfigurationChange",
    "ModelDescriptor",
    "LoadedDocument",
    "PrivacyFilter",
    "ProviderError",
    "ProviderDescriptor",
    "ProviderRole",
    "ProviderSelection",
    "QueryCandidateSnapshot",
    "QueryRun",
    "QueryRunPage",
    "QueryRunRemoveRequest",
    "QueryStep",
    "RetrievalConfiguration",
    "ProviderSettings",
    "IngestionRun",
    "RemoveRequest",
    "RemoveResult",
    "RecallSnapshot",
    "RedactionResult",
    "RetrievalTrace",
    "SearchHit",
    "SnapshotDiff",
    "SourceIngestionResult",
    "SourceInput",
    "SourceRecord",
    "SourcePreview",
    "SourcePreviewItem",
    "TraceVerification",
    "load_document",
]
